# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weewx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weewx.proto',
  package='tutorial',
  serialized_pb=_b('\n\x0bweewx.proto\x12\x08tutorial\"\x83\x02\n\x0fweather_message\x12\x10\n\x08\x64\x61tetime\x18\x01 \x02(\x02\x12\x10\n\x08pressure\x18\x02 \x02(\x02\x12\x11\n\taltimeter\x18\x03 \x02(\x02\x12\x0f\n\x07outTemp\x18\x04 \x02(\x02\x12\x13\n\x0boutHumidity\x18\x05 \x02(\x02\x12\x11\n\twindSpeed\x18\x06 \x02(\x02\x12\x0f\n\x07windDir\x18\x07 \x02(\x02\x12\x10\n\x08windGust\x18\x08 \x02(\x02\x12\x13\n\x0bwindGustDir\x18\t \x02(\x02\x12\x10\n\x08rainRate\x18\n \x02(\x02\x12\x0c\n\x04rain\x18\x0b \x02(\x02\x12\x10\n\x08\x64\x65wpoint\x18\x0c \x02(\x02\x12\x16\n\x0emodem_MB_usage\x18\r \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEATHER_MESSAGE = _descriptor.Descriptor(
  name='weather_message',
  full_name='tutorial.weather_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='tutorial.weather_message.datetime', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='tutorial.weather_message.pressure', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altimeter', full_name='tutorial.weather_message.altimeter', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outTemp', full_name='tutorial.weather_message.outTemp', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outHumidity', full_name='tutorial.weather_message.outHumidity', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windSpeed', full_name='tutorial.weather_message.windSpeed', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windDir', full_name='tutorial.weather_message.windDir', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windGust', full_name='tutorial.weather_message.windGust', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windGustDir', full_name='tutorial.weather_message.windGustDir', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rainRate', full_name='tutorial.weather_message.rainRate', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rain', full_name='tutorial.weather_message.rain', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dewpoint', full_name='tutorial.weather_message.dewpoint', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modem_MB_usage', full_name='tutorial.weather_message.modem_MB_usage', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=285,
)

DESCRIPTOR.message_types_by_name['weather_message'] = _WEATHER_MESSAGE

weather_message = _reflection.GeneratedProtocolMessageType('weather_message', (_message.Message,), dict(
  DESCRIPTOR = _WEATHER_MESSAGE,
  __module__ = 'weewx_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.weather_message)
  ))
_sym_db.RegisterMessage(weather_message)


# @@protoc_insertion_point(module_scope)
